_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 5
                - 41
                - 48
                - 49
                - 53
                - 55
                - 63
            "2":
                - 1
                - 5
                - 41
                - 48
                - 49
                - 53
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": darwin-arm64
batch_size:
    value: 2
epochs:
    value: 2
lr:
    value: 0.0001
model:
    value: VMUNetV2
